/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parchatemetro;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Sarah
 */
public class Comentario extends javax.swing.JFrame {

    /**
     * Creates new form Comentario
     */
    public Comentario() {
        initComponents();
        this.setLocationRelativeTo(null);
        muestraTextoUsuarioPrueba.setEditable(false);
          //-------------------------Redireccion de horarios--------------------------
        horarios.addMouseListener(new MouseAdapter() {

            public void mouseClicked(MouseEvent e) {
                // Hacer visible la otra pestaña
                horarios otraPestana = new horarios();
                otraPestana.setVisible(true);
                dispose();
            }
        });
          //-------------------------Redireccion de casita--------------------------
        
        iconoCasita.addMouseListener(new MouseAdapter() {

            public void mouseClicked(MouseEvent e) {
                // Hacer visible la otra pestaña
                casita otraPestana = new casita();
                otraPestana.setVisible(true);
                dispose();
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonPublicar = new javax.swing.JButton();
        usuario = new javax.swing.JLabel();
        usuarioPrueba = new javax.swing.JLabel();
        textoUsuario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        muestraTextoUsuarioPrueba = new javax.swing.JTextArea();
        horarios = new javax.swing.JLabel();
        iconoCasita = new javax.swing.JLabel();
        Pantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonPublicar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonPublicar.setText("Publicar");
        botonPublicar.setBorderPainted(false);
        botonPublicar.setContentAreaFilled(false);
        botonPublicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPublicarActionPerformed(evt);
            }
        });
        jPanel1.add(botonPublicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 424, -1, 50));

        usuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usuario.setText("USUARIO:");
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        usuarioPrueba.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usuarioPrueba.setText("Usuario Prueba:");
        jPanel1.add(usuarioPrueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));
        jPanel1.add(textoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 170, 30));

        muestraTextoUsuarioPrueba.setColumns(20);
        muestraTextoUsuarioPrueba.setRows(5);
        jScrollPane1.setViewportView(muestraTextoUsuarioPrueba);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 240, 90));

        horarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Horarios.png"))); // NOI18N
        jPanel1.add(horarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 60, 20));

        iconoCasita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/casa.png"))); // NOI18N
        jPanel1.add(iconoCasita, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        Pantalla.setBackground(new java.awt.Color(255, 255, 255));
        Pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagenFondo.png"))); // NOI18N
        Pantalla.setText("jLabel1");
        jPanel1.add(Pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPublicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPublicarActionPerformed
    // Obtener el comentario ingresado por el usuario
    String comentario = textoUsuario.getText(); 

    // Obtener el texto actual del JTextArea
    String textoActual = muestraTextoUsuarioPrueba.getText();

    // Agregar el nuevo comentario al texto actual con un String de usuario adelante de cada comentario
    String comentarios =  textoActual + "Usuario: " + comentario;

    // Estable el espacio entre los comentarios
    muestraTextoUsuarioPrueba.setText( comentarios + "\n");
    
    // Mostrar un mensaje de éxito
    JOptionPane.showMessageDialog(this, "Comentario guardado exitosamente");

    // Limpiar el campo de texto donde el usuario ingresa el comentario que quiere que se muestre
    textoUsuario.setText("");    
    }//GEN-LAST:event_botonPublicarActionPerformed
public void muestraTextoUsuarioVacio (java.awt.event.ActionEvent evt){
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comentario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comentario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comentario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comentario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comentario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pantalla;
    private javax.swing.JButton botonPublicar;
    private javax.swing.JLabel horarios;
    private javax.swing.JLabel iconoCasita;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea muestraTextoUsuarioPrueba;
    private javax.swing.JTextField textoUsuario;
    private javax.swing.JLabel usuario;
    private javax.swing.JLabel usuarioPrueba;
    // End of variables declaration//GEN-END:variables

    private void comentarios(String string) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
